import Head from "next/head";
import Image from "next/image";
import { HiCheckCircle, HiChevronRight, HiMail } from "react-icons/hi";

const applications = [
  {
    applicant: {
      name: "iPhone 13",
      email: "ricardo.cooper@example.com",
      imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13.jpg",
    },
    date: "2020-01-07",
    dateFull: "January 7, 2020",
    stage: "Completed phone screening",
    href: "#",
  },
  {
    applicant: {
      name: "Kristen Ramos",
      email: "kristen.ramos@example.com",
      imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13.jpg",
    },
    date: "2020-01-07",
    dateFull: "January 7, 2020",
    stage: "Completed phone screening",
    href: "#",
  },
  {
    applicant: {
      name: "Ted Fox",
      email: "ted.fox@example.com",
      imageUrl: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13.jpg",
    },
    date: "2020-01-07",
    dateFull: "January 7, 2020",
    stage: "Completed phone screening",
    href: "#",
  },
];

export default function Home({ phones }) {
  console.log({ phones });
  return (
    <div>
      <Head>
        <title>Phone Catalog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-50">
        <div className="max-w-7xl mx-auto min-h-screen">
          <h1 className="font-bold text-5xl tracking-tight text-center py-12">
            Phone Catalog
          </h1>

          <div className="bg-white shadow overflow-hidden sm:rounded-md">
            <ul role="list" className="divide-y divide-gray-200">
              {applications.map((application) => (
                <li key={application.applicant.email}>
                  <a href={application.href} className="block hover:bg-gray-50">
                    <div className="flex items-center px-4 py-4 sm:px-6">
                      <div className="min-w-0 flex-1 flex items-center">
                        <div className="flex-shrink-0">
                          <img
                            className="h-12 w-10"
                            src={application.applicant.imageUrl}
                            alt=""
                          />
                        </div>
                        <div className="min-w-0 flex-1 px-4 md:grid md:grid-cols-2 md:gap-4">
                          <div>
                            <p className="text-sm font-medium text-indigo-600 truncate">
                              {application.applicant.name}
                            </p>
                            <p className="mt-2 flex items-center text-sm text-gray-500">
                              <HiMail
                                className="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400"
                                aria-hidden="true"
                              />
                              <span className="truncate">
                                {application.applicant.email}
                              </span>
                            </p>
                          </div>
                          <div className="hidden md:block">
                            <div>
                              <p className="text-sm text-gray-900">
                                Applied on{" "}
                                <time dateTime={application.date}>
                                  {application.dateFull}
                                </time>
                              </p>
                              <p className="mt-2 flex items-center text-sm text-gray-500">
                                <HiCheckCircle
                                  className="flex-shrink-0 mr-1.5 h-5 w-5 text-green-400"
                                  aria-hidden="true"
                                />
                                {application.stage}
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div>
                        <HiChevronRight
                          className="h-5 w-5 text-gray-400"
                          aria-hidden="true"
                        />
                      </div>
                    </div>
                  </a>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/api/phones");
  const phones = await res.json();

  return {
    props: {
      phones,
    },
  };
}
